make lofreq compatible with vcf2maf
LCR-BCCRC/lcr-modules pull request #139
Opened 2020-11-16 17:17 UTC by Kdreval

The Lofreq outputs vcf file in the format that is not compatible with vcf2maf to populate `t_depth`, `t_ref_counts`, `t_alt_counts`. The reason is that `DP` and `DP4` columns need to be in the `FORMAT` field instead of `INFO`. I have followed suggestions from Lofreq developers in [this](https://github.com/CSB5/lofreq/issues/57) issue and vcf2maf developers in [this](https://github.com/mskcc/vcf2maf/issues/167) issue to modify the Lofreq outputs. By implementing changes to the filtering script, I made sure vcf files will be compatible with vcf2maf.

2020-11-18 00:07 UTC, lkhilton commented
I am not qualified to review something so Perl-y! @rdmorin?

2020-11-18 00:40 UTC, rdmorin commented
I'm not even sure I am. I hope we can simplify this. I'm seeing some code that could be reduced and simplified. @Kdreval can you send me an example of the Lofreq header before and after this manipulation is applied?

2020-11-19 19:50 UTC, Kdreval commented
I have updated the language in the latest commit, please see the updated version

2020-11-19 20:08 UTC, rdmorin requested changes
I made some edits. Can you test out this version?

2020-11-19 20:08 UTC, rdmorin commented on modules/lofreq/1.0/src/bash/lofreq_filter.sh
> +              if(/^(chr)*[\dX]+\s.+/){
I wonder if this could just forego the regex and just be:
else{
...
}

2020-12-02 00:10 UTC, rdmorin approved these changes

2020-12-02 00:10 UTC, merged