Module/oncodriveclustl/1.0
LCR-BCCRC/lcr-modules pull request #242
Opened 2022-06-29 20:42 UTC by mannycruz

# Pull Request Checklists

**Important:** When opening a pull request, keep only the applicable checklist and delete all other sections.

## Checklist for New Module

### Required

- [x] I used the cookiecutter template and updated the placeholder rules.

- [ ] The snakemake rules follow the [design guidelines](https://lcr-modules.readthedocs.io/en/latest/for_developers.html#module-rules). 

  - [ ] All references to the `rules` object (_e.g._ for input files) are wrapped with `str()`. **(I forgot again)**

- [ ] Every rule in the module is either listed under `localrules` or has the `threads` and `resources` directives.

- [x] Input and output files are being symlinked into the `CFG["inputs"]` and `CFG["outputs"]` subdirectories, respectively.

- [x] I grouped the input symlinking rule to the next job that uses the input files. 

- [x] I updated the final target rule (`*_all`) to include every output rule. **(I think?)**

- [ ] I explained important module design decisions in `CHANGELOG.md`. **(I forgot, will do!!!)**

- [x] I tested the module on real data for all supported `seq_type` values.

- [x] I updated the `default.yaml` configuration file to provide default values for each rule in the module snakefile.

- [x] I did not set any global wildcard constraints. Any/all wildcard constraints are set on a per-rule basis. 

- [x] I ensured that all symbolic links are relative and self-contained (_i.e._ do not point outside of the repository).

- [x] I replaced every value that should (or might need to) be updated in the default configuration file with `__UPDATE__`.

- [x] I recursively searched for all comments containing `TODO` to ensure none were left. For example:

  ```bash
  grep -r TODO modules/<module_name>/1.0
  ```

### If applicable

- [ ] I added more granular output subdirectories.

- [ ] I added rules to the `reference_files` workflow to generate any new reference files.

- [ ] I added subdirectories with large intermediate files to the list of `scratch_subdirectories` in the `default.yaml` configuration file.

- [ ] I updated the list of available wildcards for the input files in the `default.yaml` configuration file.

## Checklist for Updated Module

Important! If you are updating the module version, ensure the previous version of the module is restored from master.
If you want to restore a deleted file or directory from the remote master, you can use `git checkout origin/master path/to/file`,
then a `git commit` will ensure that file is tracked on your branch again.
Example:
```
mv modules/strelka/1.1 modules/strelka/1.2
git checkout origin/master modules/strelka/1.1
```

2022-06-29 20:43 UTC, mannycruz commented
There are 3 commits that should not be merged, I just added them to keep track of the previous script I had made: [c26cbd7], [718ec81], [150788e]

2022-07-06 20:14 UTC, lkhilton commented
> There are 3 commits that should not be merged, I just added them to keep track of the previous script I had made: [[c26cbd7](https://github.com/LCR-BCCRC/lcr-modules/commit/c26cbd7ee97b4a52e65c6604a4cc2b50eb7227d6)], [[718ec81](https://github.com/LCR-BCCRC/lcr-modules/commit/718ec81673d88a00ea13bf288ebbbca2011252a4)], [[150788e](https://github.com/LCR-BCCRC/lcr-modules/commit/150788e85fccdc36fd056d8774cb7c3887300ba3)]

Unfortunately you can't omit specific commits when you merge a branch with master - the complete commit history becomes part of the master branch when you merge. As long as the unnecessary files are deleted in the most recent commit they won't be part of the available code though.

2022-07-06 20:49 UTC, lkhilton reviewed
I've made some comments but I see there are duplicate files in here. Can you please delete the ones I'm not supposed to see, then commit and push those changes? If you want to keep the files you can move them out of your directory, commit the deletion, then move them back and leave them untracked after moving them back.

2022-07-06 20:49 UTC, lkhilton commented on modules/oncodriveclustl/1.0.1/config/default.yaml
> +        scratch_subdirectories: [] # Recommended: mutect2
Is the comment here carried over from another module?

2022-07-06 20:49 UTC, lkhilton commented on modules/oncodriveclustl/1.0.1/oncodriveclustl.smk
> +####
This stuff is all GAMBL-specific and really belongs in the Snakefile that you would use to launch this module. In that Snakefile you would store the samples table in the config as follows: 
```
config["lcr-modules"]["oncodriveclustl"]["samples"] = PIPELINE_SAMPLES["SAMPLES"]["oncodriveclustl"]
```

Then here in the module you can create the `RUN_SAMPLES` variable like this: 
```
RUN_SAMPLES = CFG["samples']
```

2022-07-06 20:49 UTC, lkhilton commented on modules/oncodriveclustl/1.0.1/config/default.yaml
> +            pathology: [["DLBCL","BL"],["FL","MCL","CLL"]]
This is going to require `pathology` to be a column in the input metadata frame. Could you please add a `pathology-1.0.yaml` schema to the `schema` directory in your module directory? There's an example in the `star/1.4` module for how to do this.

2022-07-06 20:49 UTC, lkhilton commented on modules/oncodriveclustl/1.0.1/config/default.yaml
> +            mrna:
I doubt you would run this module on mrna data, so you could drop this from your pairing config.

2022-07-07 15:45 UTC, mannycruz commented
Thanks Laura! I moved the first draft version of my pipeline out of the module directory and committed, now this pull request should just contain the most recent 'almost finalized' version

2022-07-11 21:24 UTC, lkhilton requested changes
Looks great! I have one suggestion for how to improve the generalizability of the sample_sets and some requests regarding the config structure.

2022-07-11 21:24 UTC, lkhilton commented on modules/oncodriveclustl/1.0/config/default.yaml
> +            prepare_mafs: "{REPODIR}/envs/gatk/gatkR.yaml"
The typical way to handle conda envs is to symlink them into the module directory and reference them with the `MODSDIR` shortcut instead of `REPODIR`. However since the yaml file for this conda env is packaged with the script, I think it would be better to leave this conda env file out of the LCR-modules directory system and instead refer to its location in the `SCRIPTSDIR`.

2022-07-11 21:24 UTC, lkhilton commented on modules/oncodriveclustl/1.0/config/default.yaml
> +        include_non_coding: False # True or False
The structure of these config values doesn't match what happens in most other modules. Scripts should be contained under a `scripts` key; the `sample_set` file should be under `inputs`, and things that are simple parameters (e.g. `sample_sets`, `genome_build`) should really be under `options`. 

Also what if a user wants different genome builds per sample_set? Perhaps a good way to structure this is as key:value pairs, e.g.: 
```
lcr-modules:
    oncodriveclustl:
        options: 
            sample_sets: 
                fl--dlbcl: "grch37"
```

It would also be really helpful to point the user to some documentation on how to configure the sample_sets file for compatibility with the module if it's already documented elsewhere.

2022-07-11 21:24 UTC, lkhilton commented on modules/oncodriveclustl/1.0/config/default.yaml
> +        include_non_coding: False # True or False
Actually, ideally the seq_types would be captured under this key:value pair model as well... something to think about how to structure.

2024-02-10 00:05 UTC, mannycruz commented
Created a new branch with updated OncodriveCLUSTL code because this branch is behind master by too many commits

2024-02-10 00:05 UTC, closed without merging